// lib/ai/gemini-provider.ts — Custom ModelProvider for Gemini via fetch
// Bypasses the `openai` package to avoid its URL.username setter
// which is blocked in the Convex action runtime.

import type {
  Model,
  ModelProvider,
  ModelRequest,
  ModelResponse,
  StreamEvent,
} from "@openai/agents";
import { Usage } from "@openai/agents";

// ─── Types for Chat Completions wire format ─────────────────────────────────────

interface ChatMessage {
  role: string;
  content: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  tool_calls?: any[];
  tool_call_id?: string;
  name?: string;
}

interface ChatTool {
  type: "function";
  function: {
    name: string;
    description?: string;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    parameters?: any;
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Extract plain text from an input item's content field.
 * The SDK may pass content as a string or as an array of typed content blocks.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function extractText(content: any): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .filter(
        (block: { type?: string }) =>
          block.type === "input_text" || block.type === "output_text",
      )
      .map((block: { text?: string }) => block.text ?? "")
      .join("\n");
  }
  return "";
}

/**
 * Convert SDK AgentInputItem[] into Chat Completions messages.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function convertInputToMessages(input: any[]): ChatMessage[] {
  const messages: ChatMessage[] = [];

  for (const item of input) {
    if (!item || typeof item !== "object") continue;

    switch (item.role) {
      case "user":
        messages.push({ role: "user", content: extractText(item.content) });
        break;

      case "assistant":
        messages.push({
          role: "assistant",
          content: extractText(item.content),
        });
        break;

      case "system":
        messages.push({ role: "system", content: extractText(item.content) });
        break;

      case "tool":
        // Function call result — sent back to the model
        messages.push({
          role: "tool",
          content: extractText(item.content) || "",
          tool_call_id: item.callId ?? item.toolCallId ?? "",
        });
        break;
    }

    // Handle function_call items (e.g., handoff calls generated by the SDK)
    if (item.type === "function_call") {
      messages.push({
        role: "assistant",
        content: "",
        tool_calls: [
          {
            id: item.callId ?? "",
            type: "function",
            function: {
              name: item.name ?? "",
              arguments: item.arguments ?? "{}",
            },
          },
        ],
      });
    }
  }

  return messages;
}

/**
 * Convert SDK SerializedTool[] + SerializedHandoff[] into Chat Completions tools.
 */
function convertTools(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  tools: any[],
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  handoffs: any[],
): ChatTool[] {
  const chatTools: ChatTool[] = [];

  for (const tool of tools) {
    if (tool.type === "function") {
      chatTools.push({
        type: "function",
        function: {
          name: tool.name,
          description: tool.description,
          parameters: tool.parameters,
        },
      });
    }
  }

  // Handoffs are exposed as function tools to the model
  for (const handoff of handoffs) {
    chatTools.push({
      type: "function",
      function: {
        name: handoff.toolName,
        description: handoff.toolDescription ?? "",
        parameters: handoff.inputJsonSchema ?? {
          type: "object",
          properties: {},
        },
      },
    });
  }

  return chatTools;
}

// ─── GeminiModel ────────────────────────────────────────────────────────────────

/**
 * A lightweight Model implementation that calls Gemini's OpenAI-compatible
 * Chat Completions endpoint directly via fetch(), avoiding the `openai`
 * npm package (which uses URL.username — blocked by Convex's runtime).
 */
class GeminiModel implements Model {
  constructor(
    private readonly apiKey: string,
    private readonly baseURL: string,
    private readonly modelName: string,
  ) {}

  async getResponse(request: ModelRequest): Promise<ModelResponse> {
    const messages = this.buildMessages(request);
    const tools = convertTools(request.tools, request.handoffs);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const body: Record<string, any> = {
      model: this.modelName,
      messages,
    };

    if (tools.length > 0) {
      body.tools = tools;
      body.tool_choice = "auto";
    }

    // Apply model settings
    const { modelSettings } = request;
    if (modelSettings.temperature !== undefined)
      body.temperature = modelSettings.temperature;
    if (modelSettings.maxTokens !== undefined)
      body.max_tokens = modelSettings.maxTokens;
    if (modelSettings.topP !== undefined) body.top_p = modelSettings.topP;

    const response = await fetch(`${this.baseURL}chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify(body),
      signal: request.signal,
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => "Unknown error");
      throw new Error(
        `Gemini API error ${response.status}: ${errorText.slice(0, 500)}`,
      );
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data = (await response.json()) as any;
    return this.parseResponse(data);
  }

  async *getStreamedResponse(
    _request: ModelRequest,
  ): AsyncIterable<StreamEvent> {
    throw new Error("Streaming not supported by GeminiModel provider");
  }

  // ─── Internal helpers ───────────────────────────────────────────────────

  private buildMessages(request: ModelRequest): ChatMessage[] {
    const messages: ChatMessage[] = [];

    // System instructions
    if (request.systemInstructions) {
      messages.push({ role: "system", content: request.systemInstructions });
    }

    // Input items
    if (typeof request.input === "string") {
      messages.push({ role: "user", content: request.input });
    } else if (Array.isArray(request.input)) {
      messages.push(...convertInputToMessages(request.input));
    }

    return messages;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private parseResponse(data: any): ModelResponse {
    const choice = data.choices?.[0];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const output: any[] = [];

    if (choice?.message) {
      const { message } = choice;

      // Assistant text content
      if (message.content) {
        output.push({
          type: "message",
          role: "assistant",
          status: "completed",
          content: [{ type: "output_text", text: message.content }],
        });
      }

      // Tool calls (function calls or handoff triggers)
      if (message.tool_calls && Array.isArray(message.tool_calls)) {
        for (const tc of message.tool_calls) {
          output.push({
            type: "function_call",
            callId: tc.id,
            name: tc.function.name,
            arguments: tc.function.arguments,
            status: "completed",
          });
        }
      }
    }

    // Build usage
    const usageData = {
      requests: 1,
      inputTokens: data.usage?.prompt_tokens ?? 0,
      outputTokens: data.usage?.completion_tokens ?? 0,
      totalTokens: data.usage?.total_tokens ?? 0,
    };

    return {
      usage: new Usage(usageData),
      output,
    };
  }
}

// ─── GeminiModelProvider ────────────────────────────────────────────────────────

/**
 * A ModelProvider that creates GeminiModel instances.
 * Pass this to the SDK Runner via `modelProvider`.
 */
export class GeminiModelProvider implements ModelProvider {
  private readonly apiKey: string;
  private readonly baseURL: string;
  private readonly defaultModel: string;

  constructor(options: {
    apiKey: string;
    baseURL: string;
    defaultModel: string;
  }) {
    this.apiKey = options.apiKey;
    this.baseURL = options.baseURL;
    this.defaultModel = options.defaultModel;
  }

  getModel(modelName?: string): Model {
    return new GeminiModel(
      this.apiKey,
      this.baseURL,
      modelName ?? this.defaultModel,
    );
  }
}
